FROM ppc64le/golang:alpine

RUN apk --no-cache add git unzip && \
    go get -d -v github.com/hashicorp/terraform && \
    go install ./src/github.com/hashicorp/terraform/tools/terraform-bundle

COPY terraform-bundle.hcl .

RUN terraform-bundle package terraform-bundle.hcl && \
    mkdir -p terraform-bundle && \
    unzip -d terraform-bundle terraform_*.zip

RUN mkdir -p $GOPATH/src/github.com/IBM-Cloud && cd $GOPATH/src/github.com/IBM-Cloud && git clone git@github.com:IBM-Cloud/terraform-provider-ibm.git 
RUN cd $GOPATH/src/github.com/IBM-Cloud/terraform-provider-ibm && make build && cp *  ~/.terraform.d/plugins


ARG ANSIBLE_VERSION="2.10.2"

LABEL maintainer="bmarolleau"
LABEL ansible_version=${ANSIBLE_VERSION}

RUN apt-get update \
    && apt-get install -y ansible curl python3 python3-pip python3-boto unzip 
   # \
   # && curl -LO https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_ppc64le.zip \
   # && curl -LO https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_ppc64le.zip \
   # && unzip '*.zip' -d /usr/local/bin \
   # && rm *.zip

CMD    ["/bin/bash"]
